version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: task
      MYSQL_USER: root
      MYSQL_PASSWORD: 
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      TAKE_FILE_OWNERSHIP: "true"
      network.host: "0.0.0.0"
      http.port: "9200"
      transport.host: localhost
      transport.tcp.port: "9300"
      xpack.ml.enabled: "false"
    ports:
    - "9200:9200"
    - "9300:9300"
    ulimits:
     nofile:
       soft: "65536"
       hard: "65536"  
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elastic
    links: 
      - db
      - elastic         
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
      ELASTIC_HOST: elastic
      ELASTIC_PORT: "9300"   